name: test-build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install libudev-dev
      run: sudo apt-get install -y libudev-dev
    - name: Test
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose
